# Generated by Django 4.1.3 on 2022-12-08 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Gesundheitsakte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
