# Generated by Django 4.1.3 on 2022-12-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesundheitsakte', '0002_myuuidmodel_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
